[package]
name = "fuse-vfs"
version = "0.1.0"
edition = "2021"

[dependencies]
fuser = "0.15.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[dev-dependencies]
syscalls = { version = "0.6.18", features = ["aarch64"] }
